#!/bin/bash
echo "Введите ссылку на репозиторий"
read link
echo "Input: $link"
mkdir repo
cd repo
git clone $link
mkdir ../repo_clone
mv * ../repo_clone/
rmdir ../repo
chmod -R 500 ../repo_clone/
echo "Лабаратоная работа 1 выполнена"

